force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Closing_Date__c.field-meta.xml
<CustomField>
    <fullName>Closing_Date__c</fullName>
    <label>Closing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Number_of_Closed_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Closed_Accepted__c</fullName>
    <label>Number of Closed - Accepted</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Number_of_Closed_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Closed_Rejected__c</fullName>
    <label>Number of Closed - Rejected</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AsynchronousExercise3SecondQueue.cls
public class AsynchronousExercise3SecondQueue implements Queueable{
    public List<Position__c> positionList = new List<Position__c>();
    
    public AsynchronousExercise3SecondQueue(List<Position__c> posList){
        this.positionList = posList;
    }
    
    public void execute(QueueableContext context) {
        List<Job_Application__c> jobList = new List<Job_Application__c>([SELECT Id, Stage__c, Position__c
                                                                         FROM Job_Application__c
                                                                         WHERE Position__c IN :this.positionList]);
        //empty map, populate during jobSorting
        Map<Id, List<Job_Application__c>> jobMap = new Map<Id, List<Job_Application__c>>();
        
        // sort jobApp based on Position__c
        for(Job_Application__c jobSort : jobList){
            //check if map contains key with Position__c
            if(jobMap.containsKey(jobSort.Position__c)){
                jobMap.get(jobSort.Position__c).add(jobSort);
            } else {
                jobMap.put(jobSort.Position__c, New List<Job_Application__c>());
                jobMap.get(jobSort.Position__c).add(jobSort);
                //jobMap.put(Position__c, new List<Job_Application__c> {jobSort});
            }
        }
        
        for(Position__c pos : positionList){
            integer numClosedAccepted = 0;
        	integer numClosedRejected = 0;
            
            if(jobMap.containsKey(pos.Id)){
                for(Job_Application__c jobApp : jobMap.get(pos.Id)){
                    if(jobApp.Stage__c == 'Closed - Accepted'){
                        numClosedAccepted++;
                    }
                    else if(jobApp.Stage__c == 'Closed - Rejected'){
                        numClosedRejected++;
                    }
                }
                pos.Number_of_Closed_Accepted__c = numClosedAccepted;
                pos.Number_of_Closed_Rejected__c = numClosedRejected;
            }
        }
        update positionList;
        
    }
}

//Execute
/*Map<Id, Position__c> mapPos = new Map<Id, Position__c>([SELECT Id, Closing_Date__c, Status__c, Number_of_Closed_Accepted__c, Number_of_Closed_Rejected__c FROM Position__c WHERE Closing_Date__c = TODAY);
System.enqueueJob(new AsynchronousExercise3(mapPos.keySet()));*/