force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Closing_Date__c.field-meta.xml
<CustomField>
    <fullName>Closing_Date__c</fullName>
    <label>Closing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Number_of_Closed_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Closed_Accepted__c</fullName>
    <label>Number of Closed - Accepted</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Number_of_Closed_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Closed_Rejected__c</fullName>
    <label>Number of Closed - Rejected</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AsynchronousExercise1.cls
public class AsynchronousExercise1 implements Database.Batchable<sObject> {
    //start
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(
            [SELECT Id, Number_Of_Closed_Accepted__c, Number_Of_Closed_Rejected__c, 
                 (SELECT Id, Position__c, Stage__c
                  FROM Job_Applications__r 
                  WHERE Stage__c = 'Closed - Accepted' OR Stage__c = 'Closed - Rejected') 
             FROM Position__c 
             WHERE Closing_Date__c = TODAY]
        );
    }
    
    //execute
    public void execute(Database.BatchableContext BC, List<Position__c> scope){
        List<Position__c> posList = new List<Position__c>();        
        
        for(Position__c pos : scope){
            integer numClosedAccepted = 0;
        	integer numClosedRejected = 0;
            
            pos.Status__c = 'Closed';
            
            for(Job_Application__c jobApp : pos.Job_Applications__r){
                if(jobApp.Stage__c == 'Closed - Accepted'){
                    numClosedAccepted++;
                }
                else if(jobApp.Stage__c == 'Closed - Rejected'){
                    numClosedRejected++;
                }
            }
            pos.Number_of_Closed_Accepted__c = numClosedAccepted;
            pos.Number_of_Closed_Rejected__c = numClosedRejected;
            
            posList.add(pos);
        }
        update posList;
    }
    
    //finish
    public void finish(Database.BatchableContext BC){
        
    }
}

/*AsynchronousExercise1 ex1 = new AsynchronousExercise1();
Database.executeBatch(ex1);*/