force-app/main/default/objects/Increase_Rate__c/Increase_Rate__c.object-meta.xml
<CustomObject>
    <label>Increase Rate</label>
    <nameField>
        <displayFormat>INC-{0000}</displayFormat>
        <label>Increase Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Increase Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Increase_Rate__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Increase Category 1</fullName>
            </value>
            <value>
                <fullName>Increase Category 2</fullName>
            </value>
            <value>
                <fullName>Increase Category 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Increase_Rate__c/fields/End_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Effective_Date__c</fullName>
    <label>End Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Increase_Rate__c/fields/Increase_Rate__c.field-meta.xml
<CustomField>
    <fullName>Increase_Rate__c</fullName>
    <label>Increase Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Increase_Rate__c/fields/Increase_Type__c.field-meta.xml
<CustomField>
    <fullName>Increase_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Increase Type</label>
    <referenceTo>Increase_Type__c</referenceTo>
    <relationshipLabel>Increase Rates</relationshipLabel>
    <relationshipName>Increase_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Increase_Rate__c/fields/Start_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Effective_Date__c</fullName>
    <label>Start Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Increase_Type__c/Increase_Type__c.object-meta.xml
<CustomObject>
    <label>Increase Type</label>
    <nameField>
        <label>Increase Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Increase Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IncreaseRateTriggerTest.cls
@isTest
private class IncreaseRateTriggerTest {

    @isTest
    private static void newIncreaseRate(){
        //Arrange
        Increase_Type__c it = new Increase_Type__c();
        it.Name = 'Test';
        Insert it;
            
		Increase_Rate__c ir = new Increase_Rate__c();  
        ir.Active__c = true;
        ir.Increase_Type__c = it.Id;
        ir.Start_Effective_Date__c = date.parse('07/01/2022');
        ir.End_Effective_Date__c = date.parse('07/31/2022');
        ir.Category__c = 'Increase Category 1';
        ir.Increase_Rate__c = 0.10;
		Insert ir;
        
        //Act
        Test.startTest();
        
        try {
            Increase_Rate__c ir2 = new Increase_Rate__c();  
            ir2.Active__c = true;
            ir2.Increase_Type__c = it.Id;
            ir2.Start_Effective_Date__c = date.parse('07/15/2022');
            ir2.End_Effective_Date__c = date.parse('07/20/2022');
            ir2.Category__c = 'Increase Category 1';
            ir2.Increase_Rate__c = 0.10;
            Insert ir2;
        
        Test.stopTest();
        } catch (Exception e){
            //Assert
            system.assertEquals(true, e.getMessage().contains('existing increase'));
        }        
    }
}