force-app/main/default/objects/Increase_Rate__c/Increase_Rate__c.object-meta.xml
<CustomObject>
    <label>Increase Rate</label>
    <nameField>
        <displayFormat>INC-{0000}</displayFormat>
        <label>Increase Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Increase Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Increase_Rate__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Increase Category 1</fullName>
            </value>
            <value>
                <fullName>Increase Category 2</fullName>
            </value>
            <value>
                <fullName>Increase Category 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Increase_Rate__c/fields/End_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Effective_Date__c</fullName>
    <label>End Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Increase_Rate__c/fields/Increase_Rate__c.field-meta.xml
<CustomField>
    <fullName>Increase_Rate__c</fullName>
    <label>Increase Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Increase_Rate__c/fields/Increase_Type__c.field-meta.xml
<CustomField>
    <fullName>Increase_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Increase Type</label>
    <referenceTo>Increase_Type__c</referenceTo>
    <relationshipLabel>Increase Rates</relationshipLabel>
    <relationshipName>Increase_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Increase_Rate__c/fields/Start_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Effective_Date__c</fullName>
    <label>Start Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Increase_Type__c/Increase_Type__c.object-meta.xml
<CustomObject>
    <label>Increase Type</label>
    <nameField>
        <label>Increase Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Increase Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IncreaseRateTriggerHandler.cls
public class IncreaseRateTriggerHandler {
	
    //Exercise 6
    public static void newIncreaseRate(List<Increase_Rate__c> newList){
        for(Increase_Rate__c newIncRate: newList){
           List<Increase_Rate__c> ExistingIncRate = [
               SELECT Start_Effective_Date__c, End_Effective_Date__c 
               FROM Increase_Rate__c 
               WHERE Increase_type__c = :newIncRate.Increase_type__c 
               AND Category__c = :newIncRate.Category__c 
               AND Active__c = :newIncRate.Active__c
           ];
           for(Increase_Rate__c checkIncRate : ExistingIncRate){
               if(((checkIncRate.Start_Effective_Date__c <= newIncRate.Start_Effective_Date__c 
                    && checkIncRate.End_Effective_Date__c >= newIncRate.Start_Effective_Date__c) 
                   || (checkIncRate.Start_Effective_Date__c <= newIncRate.End_Effective_Date__c 
                       && checkIncRate.End_Effective_Date__c >= newIncRate.End_Effective_Date__c)) 
                  && checkIncRate.Id <> newIncRate.Id){
                   newIncRate.addError('An existing increase rate record cover the same dates');
               }
           }
       }
    }
}