force-app/main/default/objects/Position__c/fields/Closing_Date__c.field-meta.xml
<CustomField>
    <fullName>Closing_Date__c</fullName>
    <label>Closing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Number_of_Closed_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Closed_Accepted__c</fullName>
    <label>Number of Closed - Accepted</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Number_of_Closed_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Closed_Rejected__c</fullName>
    <label>Number of Closed - Rejected</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AsynchronousExercise3.cls
public class AsynchronousExercise3 implements Queueable{
    public Set<Id> positionSet = new Set<Id>();
    
    public AsynchronousExercise3(Set<Id> posSet){
        this.positionSet = posSet;
    }
    
    public void execute(QueueableContext context) {
        List<Position__c> posList = [SELECT Id, Closing_Date__c, Status__c, Number_of_Closed_Accepted__c, Number_of_Closed_Rejected__c
                                     FROM Position__c 
                                     WHERE Id IN :this.positionSet AND Closing_Date__c = TODAY];
        
        for(Position__c pos : posList){
            pos.Status__c = 'Closed';
        }
        update posList;

		//call queueable job        
        system.enqueueJob(new AsynchronousExercise3SecondQueue(posList));
    }
}

//Execute
/*Map<Id, Position__c> mapPos = new Map<Id, Position__c>([SELECT Id, Closing_Date__c, Status__c, Number_of_Closed_Accepted__c, Number_of_Closed_Rejected__c FROM Position__c WHERE Closing_Date__c = TODAY);
System.enqueueJob(new AsynchronousExercise3(mapPos.keySet()));*/